### ISSUE TITLE
Stack Trace Needs to Check Page Mapping

### ISSUE THREAD

**Issue by Kfeavel** [panix-os-dev-team/Panix#126]
We can cause a panic-ception when the stack trace function is called because it can try to run off into the unmapped null-lands, which is a big no-no.

**Comment by Kfeavel** [comment]
@micahswitzer How should we go about fixing this? The stack trace isn't supposed to just run off into invalid memory since it's supposed to end when the `eip` is null, which we setup in `boot.s`.

**Comment by micahswitzer** [comment]
The issue is that if the stack is corrupted, it could lead the stack trace code to de-reference a non-existent page which would lead to another panic. So the issue is not so much null values, but invalid addresses which we *should* be able to check for.
