### ISSUE TITLE
Move Code Into Debug Ifdefs

### ISSUE THREAD

**Issue by Kfeavel** [panix-os-dev-team/Panix#134]
Printing is an extremely slow process, so if we want to keep Panix running as fast as possible, especially when doing operating related to paging, it is important to move debugging code into an ifdef block. This allows us to still debug by compiling with 
`-DDEBUG` while making minimal edits.

```
#if defined(DEBUG)
...
#endif
```

**Comment by micahswitzer** [comment]
Is it better to use `#if defined(XXXX)`, or `#ifdef XXXX`? You mention one in the title and the other in the body.

I'm used to using `#ifdef`, but you've been writing more C than me these days.

**Comment by Kfeavel** [comment]
The nice thing about using `#if defined(...)` is that it allows for multiple conditions instead of just one, so I guess it's a matter of going with what is flexible vs. what is more widely used.

**Comment by Kfeavel** [comment]
Resolved
