### ISSUE TITLE
Migrate To New Build System

### ISSUE THREAD

**Issue by Kfeavel** [panix-os-dev-team/Panix#149]
Make is really annoying to maintain. It's also somewhat antiquated compared to CMake or Meson.

**Comment by micahswitzer** [comment]
We're going with CMake as Meson does not support globbing.

**Comment by Kfeavel** [comment]
Turns out CMake has some assumptions that don't make it ideal for our use. SCons or rethinking our Makefile from the ground up seem to be the best options at this point.

**Comment by Kfeavel** [comment]
We need to migrate all of the Panix kernel compilation into a Makefile in the kernel directory. From there we need to have a master Makefile that compiles all libraries and then the kernel.

**Comment by Kfeavel** [comment]
Merged with #150
