### ISSUE TITLE
Integrate Unit Tests into Main Makefile

### ISSUE THREAD

**Issue by Kfeavel** [panix-os-dev-team/Panix#158]
The tests directory already has a Makefile for compiling and running the unit tests. This should be integrated into the main Makefile in the top level of the repo.

```Makefile
TESTS = tests
.PHONY: $(TESTS)
$(TESTS):
	@$(MAKE) -C $(TESTS)
```

**Comment by Kfeavel** [comment]
Maybe unit tests should be moved to a submodule too. It would clean up the kernel repo while also making it simple enough to pull in the tests if they are desired. Thoughts @micahswitzer?

**Comment by micahswitzer** [comment]
Tests are tightly-coupled to the code that they test. There is no reason to move them unless it is to keep them with the code they are testing.

I also think that we should keep the tests makefile separate, and simply use recursive make to build them from the root makefile if desired.

**Comment by Kfeavel** [comment]
> I also think that we should keep the tests makefile separate, and simply use recursive make to build them from the root makefile if desired.

That is what I was implying with this issue.

**Comment by micahswitzer** [comment]
Ah my bad. When you said integrate, I was thinking incorporate for some reason.
