### ISSUE TITLE
Reduce repetitive code and add constants in mutex.cpp

### ISSUE THREAD

**Issue by jamesaorson** [panix-os-dev-team/Panix#166]
The `mutex.cpp` implementation file has a lot of simple repetitive code.

Two prime examples are:

1. ```c++
    if (mutex == NULL)
    {
        errno = EINVAL;
        return -1;
    }
2. ```c++
    if (__atomic_test_and_set(&mutex->locked, __ATOMIC_RELEASE))
    {
        errno = EINVAL;
        return -1;
    }

Also, throughout the file there are a lot of "magic numbers". There is no reason to use raw `int` return types when we could use something like
```c++
enum class MutexResult {
    success = 0,
    error = -1,
};
```

**Comment by Kfeavel** [comment]
I'm curious to know what Micah's input on this is, because I wouldn't consider `0` and `-1` return codes "magic numbers" given that they're the standard for basically all C & C++ standard libraries. Masking them behind an `enum` seems unnecessary in my opinion. Thoughts, @micahswitzer?

**Comment by Kfeavel** [comment]
Additionally, while there may be repeated code, would it not be more expensive to make an additional function call instead of just keeping the code as is? I'm not necessary disagreeing that it is repetitive, I'm just curious as to whether or not more abstraction would be as efficient.

Edit: We could make the function inline. That would avoid actually making a function call.

**Comment by jamesaorson** [comment]
> Additionally, while there may be repeated code, would it not be more expensive to make an additional function call instead of just keeping the code as is? I'm not necessary disagreeing that it is repetitive, I'm just curious as to whether or not more abstraction would be as efficient.
> 
> Edit: Would you recommend defining the repetitive code as a macro as to avoid calling a function?

This is 100% a good use for a macro. Even if we were not using macros, putting `inline` in front of the function would encourage the compiler to inline it anyways.

**Comment by jamesaorson** [comment]
> I'm curious to know what Micah's input on this is, because I wouldn't consider `0` and `-1` return codes "magic numbers" given that they're the standard for basically all C & C++ standard libraries. Masking them behind an `enum` seems unnecessary in my opinion. Thoughts, @micahswitzer?

I know that it is the standard, but frankly I hate it. I find myself always wondering which is going to be an error or a success.
Also, in C++ 0 is falsy and all non-zero numbers are truthy. In this case, that means that an error would be `true` in a conditional. I have personally been bitten by this multiple times, as I end up not being able to naturally chain together an if statement because of a bunch of extra `!` to handle the error cases.

**Comment by jamesaorson** [comment]
I will remove the repetitive code and use the enum for the PR in separate commits. So if the enums are voted down, I can just remove the commit.

**Comment by Kfeavel** [comment]
> > I'm curious to know what Micah's input on this is, because I wouldn't consider `0` and `-1` return codes "magic numbers" given that they're the standard for basically all C & C++ standard libraries. Masking them behind an `enum` seems unnecessary in my opinion. Thoughts, @micahswitzer?
> 
> I have personally been bitten by this multiple times, as I end up not being able to naturally chain together an if statement because of a bunch of extra `!` to handle the error cases.

That is a fair point. I used to have that opinion, but it made more sense when I thought about it more, but at the same time there are arguments that can be made as to why it's bad. We can have that discussion in another thread.

**Comment by Kfeavel** [comment]
> I will remove the repetitive code and use the enum for the PR in separate commits. So if the enums are voted down, I can just remove the commit.

I was going to make those changes but go ahead if you already have an idea of what you want to do. 👍
