### ISSUE TITLE
Refactor Boot Assembly into C

### ISSUE THREAD

**Issue by Kfeavel** [panix-os-dev-team/Panix#211]
~~The kernel boot process should be refactored so that the kernel no longer resides in the higher half of memory. This will require the program loader to support dynamic relocation, but that is a compromise that we are willing to make. The boot process will be greatly simplified by not having paging code in `boot.S`. Additionally, stivale2 could be used to boot directly into parsing code before main, and a similar process can be employed for Multiboot2.~~

The new objective is to convert as much boot assembly into C as possible. All the code necessary to boot into the higher half show be located in the `.early_*` sections.

**Comment by Kfeavel** [comment]
The alternative is to make a two stage loader that parses the bootloader information and then makes it available to the higher half kernel. We're almost there already given how `boot.S` does paging already, so this is a decision we have to make.

**Comment by Kfeavel** [comment]
The stivale2 and multiboot2 headers should be defined in C and moved out of assembly. Pinging @micahswitzer on this one since he wrote the original.

Information available here:

https://wiki.osdev.org/Multiboot

**Comment by micahswitzer** [comment]
Yeah I agree we should do this. I'm sad to see my beautiful NASM go :'(

**Comment by Kfeavel** [comment]
> Yeah I agree we should do this. I'm sad to see my beautiful NASM go :'(

As dumb as it sounds, throwing the code into Ghidra and getting a rough idea of what the current assembly looks like in C might be a good way to start.

**Comment by micahswitzer** [comment]
`objdump -d` is another way to do that, although not nearly as pretty (or interactive)

**Comment by the-grue** [comment]
You can assign this to me and I'll try to work on it over this weekend.

**Comment by Kfeavel** [comment]
> You can assign this to me and I'll try to work on it over this weekend.

Awesome, thank you! Hopefully the recent architecture changes I made will be helpful as well.

**Comment by the-grue** [comment]
My apologies, I am not going to have time to work on this anytime soon.  I am going to unassign myself for now.  If it is still available when I have some free time, I will take it up again.  In the meantime, the assembler code should continue to work fine.

**Comment by Kfeavel** [comment]
@the-grue it's all good, totally understand!

I've been trying to decide whether or not having multiboot2 support is worth it, which would also have a big impact on this task.

Thanks for all you've done, it's been a big help!

**Comment by Kfeavel** [comment]
Making note of this before I forget:

@micahswitzer and I agree the best course of action would to be to write some sort of chainloader that is designed to enable paging and map in the higher half kernel. The kernel could simply include the chainloader as a library that would be linked into the lower half and provide an `_entry` symbol.

Can start on this once #325 is completed since that will help with multiple projects / architectures a lot.
