### ISSUE TITLE
Use Unix Epoch for RTC & Create `time.h`

### ISSUE THREAD

**Issue by Kfeavel** [panix-os-dev-team/Panix#227]
Currently there is no way to get information out of the RTC driver. It can only print it to screen. `time.h` should provide the commonly used functions as defined by the POSIX spec (found [here](https://pubs.opengroup.org/onlinepubs/007908775/xsh/time.h.html)) along with `stuct tm`. All communication with the RTC driver should be in order to get a Unix Epoch that can be used for other time conversion elsewhere.

**Comment by Kfeavel** [comment]
See [limine-bootloader/limine/stage23/lib/time.c](https://github.com/limine-bootloader/limine/blob/ac9ddc7cddf34071d9c357198f379645a586d32d/stage23/lib/time.c) for a good example.

**Comment by Kfeavel** [comment]
Assigning to @mauryafunez since this would be a good beginner's task for him.

**Comment by Kfeavel** [comment]
Unassigned @mauryafunez since we have some new contributors who might want to take this issue on.

**Comment by Jmallone** [comment]
Assign me to this issue, i'll try code :smiley:

**Comment by Jmallone** [comment]
I have a doubt about this, rtc.cpp would just provide the epoch value and time.cpp would convert this epoch number to human-readable date and fill the tm structure?
![epoch](https://user-images.githubusercontent.com/6977257/126911088-65817eae-8c26-4026-8b4d-af389fc368c6.png)

**Comment by Kfeavel** [comment]
> I have a doubt about this, rtc.cpp would just provide the epoch value and time.cpp would convert this epoch number to human-readable date and fill the tm structure?

Yeah. I would actually prefer to have a `Time` class instead of a `struct tm`, but it would serve the same purpose. Your diagram pretty much describes what should happen. Good job!

Any comments / recommendations, @micahswitzer?

**Comment by Jmallone** [comment]
Maybe [this](https://github.com/sidsingh78/EPOCH-to-time-date-converter) and [that](https://www.oryx-embedded.com/doc/date__time_8c_source.html) is interesting for the `time.cpp`

**Comment by Kfeavel** [comment]
I would reference [Limine's code](https://github.com/limine-bootloader/limine/blob/trunk/stage23/lib/time.c) for an example of how to get the unix epoch.
