### ISSUE TITLE
Wrong macro used for loop condition in paging.cpp:initDirectory()

### ISSUE THREAD

**Issue by vannaka** [panix-os-dev-team/Panix#386]
https://github.com/XyrisOS/xyris/blob/adf3ae0afff96e621f22f5f2c49e58e8d7b59203/Kernel/Memory/paging.cpp#L134

I believe the upper bound for the iterator of this for loop is meant to be `ARCH_PAGE_TABLE_ENTRIES`. The current code works because the two macros happen to have the same value.

**Comment by Kfeavel** [comment]
You would be correct! Thank you for opening an issue, I'll merge in a fix soon.
