### ISSUE TITLE
Move Functions to Their Proper Locations

### ISSUE THREAD

**Issue by Kfeavel** [panix-os-dev-team/Panix#80]
**Is your feature request related to a problem?**
A lot of the standard library functions implemented are not in the correct, standard header.

**Describe the feature request in detail**
All functions should move to the appropriate header. For information as to what goes where, reference [Wikipedia](https://en.wikipedia.org/wiki/C_standard_library).

**Additional context**
n/a

**Comment by micahswitzer** [comment]
If we're following the spec, wouldn't these technically be in the root directory and not in `lib/`?

**Comment by Kfeavel** [comment]
> If we're following the spec, wouldn't these technically be in the root directory and not in `lib/`?

True. Is that how the sysroot works / is structured on other systems?
