### ISSUE TITLE
Move Docker Container to Arch Linux

### ISSUE THREAD

**Issue by Kfeavel** [panix-os-dev-team/Panix#95]
Our current Docker container is a _**thicc**_ 1.87 GB because of ~Debian~ *the distro which shall not be named*, so we would like to force it to go on a diet and lose some that that thiccness. Alpine with GNU instead of MUSL seems to be the perfect replacement.

**Comment by jamesaorson** [comment]
What about something like a slim debian? I have worked with both Alpine and slim debian before and frankly, Alpine can make things pretty complicated and it isn't nearly as stable.

Slim debian is a comparable size while also retaining compatibility with what you already have.

**Comment by Kfeavel** [comment]
Our Docker file already has FROM debian:stable-slim in it. Is that not the same thing as what you're referring to?

**Comment by jamesaorson** [comment]
That is the same one....huh, I could swear at work that it is NOWHERE near that size.

**Comment by micahswitzer** [comment]
It's very possible that we're doing something to greatly increase the size. It definitely deserves another look if we're going to start using this container seriously.

**Comment by Kfeavel** [comment]
> It's very possible that we're doing something to greatly increase the size. It definitely deserves another look if we're going to start using this container seriously.

That's kind of the thing -- neither of us use the Docker container and it was more of a "let's do this because we can" than something out of necessity. Personally, I prefer to have the tools installed on my local system since it makes updating GCC to newer versions easier (especially when I use my script). Maybe if Scuba worked on macOS I would be more inclined to use it, but ¯\\_(ツ)_/¯.

If it's something we really want to pursue we can look into it more, but otherwise we could move it into another repo or just get rid of it. Github doesn't allow deletion of containers though, so we'll always have the one that's already been published.

**Comment by jamesaorson** [comment]
> > It's very possible that we're doing something to greatly increase the size. It definitely deserves another look if we're going to start using this container seriously.
> 
> That's kind of the thing -- neither of us use the Docker container and it was more of a "let's do this because we can" than something out of necessity. Personally, I prefer to have the tools installed on my local system since it makes updating GCC to newer versions easier (especially when I use my script). Maybe if Scuba worked on macOS I would be more inclined to use it, but ¯\_(ツ)_/¯.
> 
> If it's something we really want to pursue we can look into it more, but otherwise we could move it into another repo or just get rid of it. Github doesn't allow deletion of containers though, so we'll always have the one that's already been published.

I think having a development docker is a very valuable thing for encouraging contribution. Either that, or providing a single script to set up an isolated set of dev tools.

**Comment by Kfeavel** [comment]
Arch Linux has been selected instead of Alpine given that the OSDev Wiki has instructions for Arch Linux and it's proven to work with Scuba on macOS.
