### ISSUE TITLE
Discussion: Move putc to stdio.hpp?

### ISSUE THREAD

**Issue by Kfeavel** [panix-os-dev-team/Panix#97]
Technically according to the POSIX spec, putc should go in stdio.h (in our case hpp). Should we move it there even though it's a TTY device function? I honestly don't have a problem with it.

**Comment by micahswitzer** [comment]
The declaration can absolutely go there. We're still free to organize the implementation however we desire.

**Comment by Kfeavel** [comment]
> The declaration can absolutely go there. We're still free to organize the implementation however we desire.

Awesome. The more I work on this and the more I look into standards like ANSI and POSIX, the more I want to reorganize things to conform to those standards. I'm going to go ahead and start moving things around then once #99 is merged.
