### ISSUE TITLE
Update putchar to handle ANSI cursor position

### ISSUE THREAD

**Issue by Kfeavel** [panix-os-dev-team/Panix#98]
**Is your feature request related to a problem?**
We should not have a function to print at a given location

**Describe the feature request in detail**
putchar (putc) should handle the ANSI code to move the cursor

**Additional context**
```
Esc[Line;ColumnH
Esc[Line;Columnf
```
**Cursor Position:**
Moves the cursor to the specified position (coordinates).
If you do not specify a position, the cursor moves to the home position at the upper-left corner of the screen (line 0, column 0). This escape sequence works the same way as the following Cursor Position escape sequence.

**Comment by Kfeavel** [comment]
For some reason the save and restore codes print out `s` and `u` instead of processing them as codes...

**Comment by Kfeavel** [comment]
That issue is fixed. Now I have to figure out how to use them without causing issues.

**Comment by micahswitzer** [comment]
I don't think there's a problem with having low-level functions to set the position that could be used internally for special/specific features (like status indicators), but I do agree they shouldn't be used for general-purpose printing operations.

**Comment by Kfeavel** [comment]
> I don't think there's a problem with having low-level functions to set the position that could be used internally for special/specific features (like status indicators), but I do agree they shouldn't be used for general-purpose printing operations.

Once I move putchar and everything else related to stdio into their proper position, I plan on writing some raw TTY functions like tty_write_raw, which will take a byte input and just write it. I can also add some other functions for manually adjusting cursor position, etc without needing to use ANSI codes.

**Comment by micahswitzer** [comment]
Sounds good
